spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


server:
  port: 18080


# DB 설정
dbenv:
  hp:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:3306/board
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1111
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 10
        connection-test-query: SELECT 1
        minimum-idle: 5
        connection-timeout: 100000

mybatis:
  mapper-locations: classpath:*/mapper/*.xml